server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /app/static;
    gzip_static on;
    brotli_static on;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
