import type { MetaFile } from '@/types'

export default {
  label: 'Admin',
  scrollable: true,
  collapsed: false,
  items: {
    'challenge-list': { order: 1 },
    'challenge-detail': { order: 2 },
    'challenge-update': { order: 3 },
    'challenge-delete-solve': { order: 4 },
    'challenge-delete': { order: 5 },
    upload: { order: 6 },
    'upload-query': { order: 7 },
    teams: { order: 8 },
    'team-filter': { order: 9 },
    'team-detail': { order: 10 },
    'team-update': { order: 11 },
    'team-delete': { order: 12 },
    'team-token': { order: 13 },
    verifications: { order: 14 },
    'verification-complete': { order: 15 },
    'verification-resend': { order: 16 },
    submissions: { order: 17 },
    'submission-filter': { order: 18 },
    settings: { order: 19 },
    'settings-update': { order: 20 },
    'instancer-schema': { order: 21 },
    'admin-bot-status': { order: 22 },
    'admin-bot-pull': { order: 23 },
    'admin-bot-source': { order: 24 },
    'admin-bot-complete': { order: 25 },
    'admin-bot-fail': { order: 26 },
    'admin-bot-queue-depth': { order: 27 },
    'ext-auth-list': { order: 28 },
    'ext-auth-create': { order: 29 },
    'ext-auth-delete': { order: 30 },
  },
} satisfies MetaFile
