// common
export * from './bad-body'
export * from './bad-endpoint'
export * from './bad-json'
export * from './bad-perms'
export * from './bad-rate-limit'
export * from './bad-token'
export * from './error-internal'

// auth
export * from './bad-competition-not-allowed'
export * from './bad-ctftime-token'
export * from './bad-email'
export * from './bad-email-change-division'
export * from './bad-email-no-exists'
export * from './bad-known-ctftime-id'
export * from './bad-known-email'
export * from './bad-known-name'
export * from './bad-name'
export * from './bad-registrations-disabled'
export * from './bad-token-verification'
export * from './bad-unknown-email'
export * from './bad-unknown-user'
export * from './bad-zero-auth'
export * from './good-email-set'
export * from './good-login'
export * from './good-register'
export * from './good-token'
export * from './good-verify'
export * from './good-verify-sent'

// challenges
export * from './bad-already-solved-challenge'
export * from './bad-challenge'
export * from './bad-ended'
export * from './bad-flag'
export * from './bad-not-started'
export * from './good-challenge-solves'
export * from './good-challenges'
export * from './good-flag'

// users
export * from './bad-ctftime-no-exists'
export * from './bad-division-not-allowed'
export * from './bad-avatar-file'
export * from './bad-avatar-file-size'
export * from './good-ctftime-auth-set'
export * from './good-ctftime-removed'
export * from './good-email-removed'
export * from './good-member-create'
export * from './good-member-data'
export * from './good-member-delete'
export * from './good-user-data'
export * from './good-user-self-data'
export * from './good-user-update'
export * from './good-avatar-updated'

// leaderboard
export * from './good-leaderboard'
export * from './good-leaderboard-graph'

// integrations
export * from './bad-ctftime-code'
export * from './good-client-config'
export * from './good-ctftime-leaderboard'
export * from './good-ctftime-token'

// admin
export * from './bad-data-uri'
export * from './bad-files-upload'
export * from './good-admin-challenge'
export * from './good-admin-challenges'
export * from './good-challenge-delete'
export * from './good-challenge-update'
export * from './good-files-upload'
export * from './good-uploads-query'

// v2
export * from './bad-unknown-solve-v2'
export * from './bad-user-privileged'
export * from './bad-instancer-error'
export * from './bad-discord-code-v2'
export * from './bad-discord-token-v2'
export * from './good-user-data-v2'
export * from './good-user-self-data-v2'
export * from './good-user-update-v2'
export * from './good-leaderboard-v2'
export * from './good-challenges-v2'
export * from './good-challenge-solves-v2'
export * from './good-admin-challenge-v2'
export * from './good-admin-challenges-v2'
export * from './good-challenge-update-v2'
export * from './good-challenge-solve-delete-v2'
export * from './good-files-upload-v2'
export * from './good-client-config-v2'
export * from './good-instance-status'
export * from './good-create-user-token-v2'
export * from './good-client-config-v2'
export * from './good-discord-token-v2'
