server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /app/static;
    gzip_static on;
    brotli_static on;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_connect_timeout 30s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;

    add_header Referrer-Policy "no-referrer" always;
    add_header Content-Security-Policy "default-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' 'sha256-FmtvhoF2LId/PY1wL/sgUbxDA08bYvvWTHUIEQMp604=' static.cloudflareinsights.com; connect-src 'self' cloudflareinsights.com; img-src *; frame-src https://www.youtube.com https://youtube.com https://www.youtube-nocookie.com; frame-ancestors 'self';" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;

    location ~ ^/api/v[12]/admin/upload$ {
        proxy_pass http://127.0.0.1:3000;
        client_max_body_size 0;
        proxy_request_buffering off;
    }

    # TODO(trixter-osec): we should consider setting up caching for e.g. /api/v1/challs for resiliency (if challenges don't require auth)
    location ~ ^/(api|uploads) {
        proxy_pass http://127.0.0.1:3000;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
