server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /app/static;

    # TODO(trixter-osec): we should consider setting up caching for e.g. /api/v1/challs for resiliency (if challenges don't require auth)
    location ~ ^/(api|uploads) {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:3000;
    }
}
