import adminGroup from './group'
import './routes/complete-admin-bot-job'
import './routes/create-user-token'
import './routes/delete-solve'
import './routes/fail-admin-bot-job'
import './routes/get-admin-bot-challenge-source'
import './routes/get-admin-bot-status'
import './routes/get-admin-challenge'
import './routes/get-admin-challenges'
import './routes/get-admin-settings'
import './routes/get-admin-users'
import './routes/get-instancer-schema'
import './routes/pull-admin-bot-job'
import './routes/query-uploads'
import './routes/update-admin-settings'
import './routes/update-challenge'
import './routes/upload-files'

export default adminGroup
