import type { SvelteComponent } from 'svelte'
import type { SvelteHTMLElements } from 'svelte/elements'

interface IconProps {
  width?: string
  height?: string
}

export type IconComponent = typeof SvelteComponent<
  Omit<SvelteHTMLElements['svg'], 'viewBox' | 'width' | 'height' | 'xmlns'> &
    IconProps &
    Record<`data-${string}`, string>
>

export { default as IconAlertCircleFilled } from '@iconify-svelte/tabler/alert-circle-filled'
export { default as IconAlertTriangleFilled } from '@iconify-svelte/tabler/alert-triangle-filled'
export { default as IconArrowBigLeftFilled } from '@iconify-svelte/tabler/arrow-big-left-filled'
export { default as IconArrowBigRightFilled } from '@iconify-svelte/tabler/arrow-big-right-filled'
export { default as IconAwardFilled } from '@iconify-svelte/tabler/award-filled'
export { default as IconBell } from '@iconify-svelte/tabler/bell'
export { default as IconBinaryTreeFilled } from '@iconify-svelte/tabler/binary-tree-filled'
export { default as IconBombFilled } from '@iconify-svelte/tabler/bomb-filled'
export { default as IconChartAreaLineFilled } from '@iconify-svelte/tabler/chart-area-line-filled'
export { default as IconCheck } from '@iconify-svelte/tabler/check'
export { default as IconChevronDown } from '@iconify-svelte/tabler/chevron-down'
export { default as IconChevronLeft } from '@iconify-svelte/tabler/chevron-left'
export { default as IconChevronLeftPipe } from '@iconify-svelte/tabler/chevron-left-pipe'
export { default as IconChevronRight } from '@iconify-svelte/tabler/chevron-right'
export { default as IconChevronRightPipe } from '@iconify-svelte/tabler/chevron-right-pipe'
export { default as IconChevronUp } from '@iconify-svelte/tabler/chevron-up'
export { default as IconCircle } from '@iconify-svelte/tabler/circle'
export { default as IconCircleCheckFilled } from '@iconify-svelte/tabler/circle-check-filled'
export { default as IconCircleDashed } from '@iconify-svelte/tabler/circle-dashed'
export { default as IconCircleNumber1Filled } from '@iconify-svelte/tabler/circle-number-1-filled'
export { default as IconCircleNumber2Filled } from '@iconify-svelte/tabler/circle-number-2-filled'
export { default as IconCircleNumber3Filled } from '@iconify-svelte/tabler/circle-number-3-filled'
export { default as IconCloudComputingFilled } from '@iconify-svelte/tabler/cloud-computing-filled'
export { default as IconCoins } from '@iconify-svelte/tabler/coins'
export { default as IconCopy } from '@iconify-svelte/tabler/copy'
export { default as IconCopyPlusFilled } from '@iconify-svelte/tabler/copy-plus-filled'
export { default as IconDice6Filled } from '@iconify-svelte/tabler/dice-6-filled'
export { default as IconDots } from '@iconify-svelte/tabler/dots'
export { default as IconDownload } from '@iconify-svelte/tabler/download'
export { default as IconEyeClosed } from '@iconify-svelte/tabler/eye-closed'
export { default as IconEyeFilled } from '@iconify-svelte/tabler/eye-filled'
export { default as IconFileFilled } from '@iconify-svelte/tabler/file-filled'
export { default as IconFileInfoFilled } from '@iconify-svelte/tabler/file-info-filled'
export { default as IconFileUploadFilled } from '@iconify-svelte/tabler/file-upload-filled'
export { default as IconFlagFilled } from '@iconify-svelte/tabler/flag-filled'
export { default as IconFold } from '@iconify-svelte/tabler/fold'
export { default as IconGavel } from '@iconify-svelte/tabler/gavel'
export { default as IconGripVertical } from '@iconify-svelte/tabler/grip-vertical'
export { default as IconHammer } from '@iconify-svelte/tabler/hammer'
export { default as IconHomeFilled } from '@iconify-svelte/tabler/home-filled'
export { default as IconInfoCircle } from '@iconify-svelte/tabler/info-circle'
export { default as IconInfoCircleFilled } from '@iconify-svelte/tabler/info-circle-filled'
export { default as IconKeyFilled } from '@iconify-svelte/tabler/key-filled'
export { default as IconLibraryPlusFilled } from '@iconify-svelte/tabler/library-plus-filled'
export { default as IconTableFilled } from '@iconify-svelte/tabler/table-filled'
export { default as IconLayoutListFilled } from '@iconify-svelte/tabler/layout-list-filled'
export { default as IconLoader } from '@iconify-svelte/tabler/loader'
export { default as IconLogout } from '@iconify-svelte/tabler/logout'
export { default as IconLogin } from '@iconify-svelte/tabler/login'
export { default as IconMicroscopeFilled } from '@iconify-svelte/tabler/microscope-filled'
export { default as IconMinus } from '@iconify-svelte/tabler/minus'
export { default as IconMoonFilled } from '@iconify-svelte/tabler/moon-filled'
export { default as IconPencilFilled } from '@iconify-svelte/tabler/pencil'
export { default as IconPuzzleFilled } from '@iconify-svelte/tabler/puzzle-filled'
export { default as IconSearch } from '@iconify-svelte/tabler/search'
export { default as IconSortAscendingNumbers } from '@iconify-svelte/tabler/sort-ascending-numbers'
export { default as IconSortDescendingShapesFilled } from '@iconify-svelte/tabler/sort-descending-shapes-filled'
export { default as IconSend } from '@iconify-svelte/tabler/send'
export { default as IconSettings } from '@iconify-svelte/tabler/settings'
export { default as IconSettingsFilled } from '@iconify-svelte/tabler/settings-filled'
export { default as IconSunHighFilled } from '@iconify-svelte/tabler/sun-high-filled'
export { default as IconFlag3Filled } from '@iconify-svelte/tabler/flag-3-filled'
export { default as IconTrashFilled } from '@iconify-svelte/tabler/trash-filled'
export { default as IconTrophyFilled } from '@iconify-svelte/tabler/trophy-filled'
export { default as IconUserCog } from '@iconify-svelte/tabler/user-cog'
export { default as IconUserFilled } from '@iconify-svelte/tabler/user-filled'
export { default as IconUsersPlus } from '@iconify-svelte/tabler/users-plus'
export { default as IconX } from '@iconify-svelte/tabler/x'
export { default as IconZoomQuestionFilled } from '@iconify-svelte/tabler/zoom-question-filled'
