import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type {
  AdminBotConfig,
  InstancerConfig,
} from '../../packages/db/src/index'

const rootDir = path.resolve(import.meta.dir, '../..')
const dataDir = path.join(rootDir, '.data')
const generatedConfigPath = path.join(
  rootDir,
  'rctf.d',
  'zz-dev-seed.generated.yml'
)
const staleGeneratedConfigPaths = [
  path.join(rootDir, 'rctf.d', '99-dev-seed.generated.yml'),
]
const seedOutputPath = path.join(dataDir, 'dev-seed.json')

const HOUR = 60 * 60 * 1000
const DAY = 24 * HOUR

const now = Date.now()
const startTime = now - 2 * DAY
const endTime = now + 3 * DAY

const generatedConfig = `# Generated by \`bun run dev:seed\`.
# This file is intentionally ignored by git and can be regenerated at any time.
ctfName: rCTF Dev Arena
origin: http://127.0.0.1:5173
homeContent: |
  Welcome to the seeded rCTF development arena.

  <timer></timer>
meta:
  description: Seeded local rCTF development instance
  imageUrl: https://example.com/dev.png
divisions:
  open: Open
  college: College
  high-school: High School
defaultDivision: open
startTime: ${startTime}
endTime: ${endTime}
leaderboard:
  updateInterval: 3000
  graphMaxTeams: 12
  graphWithListLimit: 100
  graphSampleTime: 3600000
instancerProvider:
  name: 'instancer/docker-instancer'
  options:
    authToken: dev-instancer-token
    apiUrl: http://127.0.0.1:1337
adminBot:
  provider:
    name: 'admin-bot/rctf-js'
    options:
      secretKey: dev-admin-bot-secret
      endpoint: http://127.0.0.1:21337
`

await mkdir(path.dirname(generatedConfigPath), { recursive: true })
await mkdir(dataDir, { recursive: true })
await Promise.all(
  staleGeneratedConfigPaths.map(file => rm(file, { force: true }))
)
await writeFile(generatedConfigPath, generatedConfig)

const [
  { config },
  dbModule,
  { Permissions },
  { createLoginVerification },
  { cacheLeaderboardAndGraph },
  { createToken, TokenKind },
  { calculateLeaderboard },
  { createRedis },
  { assertDevStorageTarget },
] = await Promise.all([
  import('../../packages/config/src/index'),
  import('../../packages/db/src/index'),
  import('../../packages/types/src/index'),
  import('../../apps/api/src/cache/auth-cache'),
  import('../../apps/api/src/cache/leaderboard'),
  import('../../apps/api/src/lib/tokens'),
  import('../../apps/api/src/services/leaderboard'),
  import('../../apps/api/src/util/redis'),
  import('./assert-storage'),
])

const {
  adminBotJobs,
  challenges,
  createDatabase,
  settings,
  solves,
  userMembers,
  users,
} = dbModule

type SeedExposeKind = InstancerConfig['expose'][number]['kind']
type SeedInstancerConfig = InstancerConfig
type SeedAdminBotConfig = AdminBotConfig

const seedExposeKind = {
  tcp: 'tcp' as SeedExposeKind,
  tcpSsl: 'tcp-ssl' as SeedExposeKind,
  http: 'http' as SeedExposeKind,
  https: 'https' as SeedExposeKind,
}

type ChallengeSeed = {
  id: string
  name: string
  category: string
  author: string
  min: number
  max: number
  difficulty: number
  sortWeight: number
  hidden?: boolean
  releaseOffsetHours?: number
  files?: { name: string; url: string; size?: number }[]
  instancerConfig?: SeedInstancerConfig
  adminBotConfig?: SeedAdminBotConfig
}

type SeedUser = {
  id: string
  name: string
  email: string
  division: string
  perms: number
  ctftimeId: string | null
  createdAt: string
  avatarUrl: string | null
  countryCode: string | null
  statusText: string | null
  banned: boolean
}

type PendingTeamSeed = {
  name: string
  email: string
  division: string
}

type SubmissionLogSeed = {
  id: string
  kind: 'flag' | 'admin_bot'
  challenge_id: string
  user_id: string
  ip: string
  result:
    | 'correct'
    | 'incorrect'
    | 'rate_limited'
    | 'already_solved'
    | 'queued'
    | 'active_job'
    | 'invalid_input'
    | 'bad_instancer_state'
  details: Record<string, unknown>
  related_id: string | null
  created_at: string
}

const rand = (() => {
  let seed = 0xc0ffee
  return () => {
    seed |= 0
    seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
})()

const clamp = (value: number, min: number, max: number) =>
  Math.min(max, Math.max(min, value))

const pick = <T>(items: readonly T[]): T =>
  items[Math.floor(rand() * items.length)]!

const slug = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

const adminBotVisitCode = `import { Challenge, type ChallengeContext } from '../src/types'

export const challenge = new Challenge({
  timeoutMilliseconds: 30_000,
  inputs: {
    url: { pattern: '^https?://.{1,200}$' },
  },
  handler: async (ctx: ChallengeContext): Promise<void> => {
    const page = await ctx.browserContext.newPage()
    const url = ctx.input.url!
    ctx.output.info('adminbot', 'visiting submitted URL', { url })
    await page.goto(url)
    await page.close()
  },
  requireInstancerInstancesRunning: false,
})
`

const instancedAdminBotCode = adminBotVisitCode.replace(
  'requireInstancerInstancesRunning: false',
  'requireInstancerInstancesRunning: true'
)

function createInstancerConfig(
  id: string,
  kind: SeedExposeKind = seedExposeKind.http,
  extendable = true
): SeedInstancerConfig {
  const containerPort =
    kind === seedExposeKind.http || kind === seedExposeKind.https ? 80 : 31337
  return {
    challengeIntegrationId: id,
    config: {
      services: {
        app: {
          image: 'traefik/whoami:latest',
          environment: {
            RCTF_CHALLENGE_ID: id,
          },
        },
      },
    },
    expose: [
      {
        kind,
        hostPrefix: slug(id),
        containerName: 'app',
        containerPort,
        title:
          kind === seedExposeKind.http || kind === seedExposeKind.https
            ? 'Web service'
            : 'Challenge service',
      },
    ],
    timeoutMilliseconds: 30 * 60 * 1000,
    extendable,
  }
}

function createAdminBotConfig(
  id: string,
  requireInstancerInstancesRunning = false
): SeedAdminBotConfig {
  return {
    code: requireInstancerInstancesRunning
      ? instancedAdminBotCode
      : adminBotVisitCode,
    inputs: {
      url: { pattern: '^https?://.{1,200}$' },
    },
    revision: `dev-seed-${slug(id)}-adminbot-v1`,
    timeoutMilliseconds: 30_000,
    requireInstancerInstancesRunning,
  }
}

const toIso = (timestamp: number) => new Date(timestamp).toISOString()

const shiftIso = (iso: string, deltaMs: number) =>
  toIso(new Date(iso).getTime() + deltaMs)

const allPermissions = Object.values(Permissions)
  .filter((value): value is number => typeof value === 'number')
  .reduce((acc, value) => acc | value, 0)

const divisions = ['open', 'college', 'high-school'] as const
const countries = [
  'US',
  'CA',
  'GB',
  'DE',
  'FR',
  'NL',
  'PL',
  'SE',
  'BR',
  'JP',
  'KR',
  'SG',
  'IN',
  'AU',
] as const
const statuses = [
  'reviewing packet captures',
  'debugging in prod',
  'collecting first bloods',
  'living in the admin panel',
  'waiting on coffee',
  'writing suspicious regex',
  'reading challenge source',
] as const

const prefixes = [
  'Null',
  'Byte',
  'Stack',
  'Cipher',
  'Kernel',
  'Packet',
  'Cache',
  'Signal',
  'Vector',
  'Heap',
  'Relay',
  'Salt',
  'Orbit',
  'Patch',
  'Socket',
  'Lambda',
  'Proof',
  'Trace',
] as const
const suffixes = [
  'Garden',
  'Foundry',
  'Collective',
  'Workshop',
  'Society',
  'Union',
  'Lab',
  'Club',
  'Crew',
  'Stack',
  'Works',
  'Studio',
] as const

const challengeSeeds: ChallengeSeed[] = [
  {
    id: 'dev-web-cookie-monster',
    name: 'Cookie Monster',
    category: 'web',
    author: 'dev-team',
    min: 100,
    max: 500,
    difficulty: 0.22,
    sortWeight: 10,
    adminBotConfig: createAdminBotConfig('dev-web-cookie-monster'),
  },
  {
    id: 'dev-web-cache-me-outside',
    name: 'Cache Me Outside',
    category: 'web',
    author: 'dev-team',
    min: 120,
    max: 500,
    difficulty: 0.38,
    sortWeight: 20,
    instancerConfig: createInstancerConfig('dev-web-cache-me-outside'),
  },
  {
    id: 'dev-web-template-tangle',
    name: 'Template Tangle',
    category: 'web',
    author: 'dev-team',
    min: 150,
    max: 500,
    difficulty: 0.62,
    sortWeight: 30,
    instancerConfig: createInstancerConfig('dev-web-template-tangle'),
    adminBotConfig: createAdminBotConfig('dev-web-template-tangle', true),
  },
  {
    id: 'dev-pwn-stack-sundae',
    name: 'Stack Sundae',
    category: 'pwn',
    author: 'dev-team',
    min: 120,
    max: 500,
    difficulty: 0.32,
    sortWeight: 40,
    files: [{ name: 'stack-sundae.tar.gz', url: '/uploads/dev/stack.tar.gz' }],
    instancerConfig: createInstancerConfig(
      'dev-pwn-stack-sundae',
      seedExposeKind.tcp
    ),
  },
  {
    id: 'dev-pwn-heap-house',
    name: 'Heap House',
    category: 'pwn',
    author: 'dev-team',
    min: 180,
    max: 500,
    difficulty: 0.72,
    sortWeight: 50,
    instancerConfig: createInstancerConfig(
      'dev-pwn-heap-house',
      seedExposeKind.tcp,
      false
    ),
  },
  {
    id: 'dev-pwn-syscall-surfing',
    name: 'Syscall Surfing',
    category: 'pwn',
    author: 'dev-team',
    min: 220,
    max: 500,
    difficulty: 0.84,
    sortWeight: 60,
  },
  {
    id: 'dev-crypto-rolling-scones',
    name: 'Rolling Scones',
    category: 'crypto',
    author: 'dev-team',
    min: 100,
    max: 500,
    difficulty: 0.2,
    sortWeight: 70,
  },
  {
    id: 'dev-crypto-lattice-latte',
    name: 'Lattice Latte',
    category: 'crypto',
    author: 'dev-team',
    min: 200,
    max: 500,
    difficulty: 0.8,
    sortWeight: 80,
  },
  {
    id: 'dev-crypto-oracle-orchard',
    name: 'Oracle Orchard',
    category: 'crypto',
    author: 'dev-team',
    min: 160,
    max: 500,
    difficulty: 0.58,
    sortWeight: 90,
  },
  {
    id: 'dev-rev-static-season',
    name: 'Static Season',
    category: 'rev',
    author: 'dev-team',
    min: 110,
    max: 500,
    difficulty: 0.28,
    sortWeight: 100,
  },
  {
    id: 'dev-rev-symbol-soup',
    name: 'Symbol Soup',
    category: 'rev',
    author: 'dev-team',
    min: 160,
    max: 500,
    difficulty: 0.55,
    sortWeight: 110,
  },
  {
    id: 'dev-rev-vm-vacation',
    name: 'VM Vacation',
    category: 'rev',
    author: 'dev-team',
    min: 240,
    max: 500,
    difficulty: 0.9,
    sortWeight: 120,
  },
  {
    id: 'dev-forensics-packet-parfait',
    name: 'Packet Parfait',
    category: 'forensics',
    author: 'dev-team',
    min: 100,
    max: 500,
    difficulty: 0.25,
    sortWeight: 130,
  },
  {
    id: 'dev-forensics-memory-market',
    name: 'Memory Market',
    category: 'forensics',
    author: 'dev-team',
    min: 170,
    max: 500,
    difficulty: 0.64,
    sortWeight: 140,
  },
  {
    id: 'dev-misc-regex-rodeo',
    name: 'Regex Rodeo',
    category: 'misc',
    author: 'dev-team',
    min: 100,
    max: 500,
    difficulty: 0.18,
    sortWeight: 150,
    adminBotConfig: createAdminBotConfig('dev-misc-regex-rodeo'),
  },
  {
    id: 'dev-misc-sanity-check',
    name: 'Sanity Check',
    category: 'misc',
    author: 'dev-team',
    min: 50,
    max: 50,
    difficulty: 0.05,
    sortWeight: 160,
  },
  {
    id: 'dev-osint-map-drift',
    name: 'Map Drift',
    category: 'osint',
    author: 'dev-team',
    min: 120,
    max: 500,
    difficulty: 0.42,
    sortWeight: 170,
  },
  {
    id: 'dev-web-release-window',
    name: 'Release Window',
    category: 'web',
    author: 'dev-team',
    min: 150,
    max: 500,
    difficulty: 0.52,
    sortWeight: 180,
    releaseOffsetHours: 8,
  },
  {
    id: 'dev-crypto-coming-soon',
    name: 'Coming Soon Cipher',
    category: 'crypto',
    author: 'dev-team',
    min: 250,
    max: 500,
    difficulty: 0.92,
    sortWeight: 190,
    releaseOffsetHours: 84,
  },
  {
    id: 'dev-hidden-admin-only',
    name: 'Hidden Admin Only',
    category: 'misc',
    author: 'dev-team',
    min: 500,
    max: 500,
    difficulty: 0.99,
    sortWeight: 200,
    hidden: true,
    instancerConfig: createInstancerConfig('dev-hidden-admin-only'),
    adminBotConfig: createAdminBotConfig('dev-hidden-admin-only'),
  },
]

const publicChallengeSeeds = challengeSeeds.filter(seed => {
  if (seed.hidden) return false
  return config.startTime + (seed.releaseOffsetHours ?? 0) * HOUR <= now
})

const teamUsers: SeedUser[] = Array.from({ length: 72 }, (_, index) => {
  const n = index + 1
  const name =
    index < prefixes.length * suffixes.length
      ? `${prefixes[index % prefixes.length]} ${
          suffixes[Math.floor(index / prefixes.length) % suffixes.length]
        }`
      : `Dev Team ${n}`
  const banned = [14, 37, 58].includes(n)

  return {
    id: `dev-team-${String(n).padStart(3, '0')}`,
    name,
    email: `${slug(name)}@dev.rctf.local`,
    division: divisions[index % divisions.length]!,
    perms: 0,
    ctftimeId: null,
    createdAt: toIso(config.startTime - (72 - index) * 37 * 60_000),
    avatarUrl: null,
    countryCode: pick(countries),
    statusText: pick(statuses),
    banned,
  }
})

const adminUsers: SeedUser[] = [
  {
    id: 'dev-admin',
    name: 'Dev Admin',
    email: 'admin@dev.rctf.local',
    division: 'open',
    perms: allPermissions,
    ctftimeId: null,
    createdAt: toIso(config.startTime - 6 * HOUR),
    avatarUrl: null,
    countryCode: 'US',
    statusText: 'seeded admin account',
    banned: false,
  },
  {
    id: 'dev-challenge-admin',
    name: 'Challenge Admin',
    email: 'challenge-admin@dev.rctf.local',
    division: 'open',
    perms:
      Permissions.challsRead |
      Permissions.challsWrite |
      Permissions.challsSolveWrite,
    ctftimeId: null,
    createdAt: toIso(config.startTime - 5 * HOUR),
    avatarUrl: null,
    countryCode: 'GB',
    statusText: 'can edit challenges and solves',
    banned: false,
  },
]

const pendingTeamRegistrations: PendingTeamSeed[] = [
  {
    name: 'Pending Team Alpha',
    email: 'pending-alpha@dev.rctf.local',
    division: 'open',
  },
  {
    name: 'Verification Queue',
    email: 'verification-queue@dev.rctf.local',
    division: 'college',
  },
  {
    name: 'Needs Email Click',
    email: 'needs-email-click@dev.rctf.local',
    division: 'high-school',
  },
  {
    name: 'Resend Target',
    email: 'resend-target@dev.rctf.local',
    division: 'open',
  },
]

const seedUsers = [...adminUsers, ...teamUsers]

const challengeRows = challengeSeeds.map(seed => ({
  id: seed.id,
  data: {
    name: seed.name,
    description: `Seeded development challenge for ${seed.category}. This gives the UI realistic rows, solve history, and leaderboard movement.`,
    category: seed.category,
    author: seed.author,
    files: seed.files ?? [],
    points: {
      min: seed.min,
      max: seed.max,
    },
    flag: `rctf{${slug(seed.name).replaceAll('-', '_')}}`,
    tiebreakEligible: seed.category !== 'misc' || seed.name !== 'Sanity Check',
    sortWeight: seed.sortWeight,
    hidden: seed.hidden ?? false,
    releaseTime:
      seed.releaseOffsetHours === undefined
        ? null
        : config.startTime + seed.releaseOffsetHours * HOUR,
    ...(seed.instancerConfig ? { instancerConfig: seed.instancerConfig } : {}),
    ...(seed.adminBotConfig ? { adminBotConfig: seed.adminBotConfig } : {}),
  },
}))
const challengeFlagById = new Map(
  challengeRows.map(challenge => [challenge.id, challenge.data.flag])
)

const solveRows: Array<{
  id: string
  challengeid: string
  userid: string
  createdat: string
  submissionip: string
}> = []
const solveKeys = new Set<string>()
const latestSolveTime = Math.min(now - 10 * 60_000, config.endTime - HOUR)

const addSolve = (
  team: SeedUser,
  challenge: ChallengeSeed,
  timestamp: number,
  challengeIndex: number
) => {
  const key = `${team.id}:${challenge.id}`
  if (solveKeys.has(key)) return
  solveKeys.add(key)
  solveRows.push({
    id: `solve-${team.id}-${challenge.id}`,
    challengeid: challenge.id,
    userid: team.id,
    createdat: toIso(timestamp),
    submissionip: `10.${(challengeIndex % 200) + 10}.${Number(team.id.slice(-3)) % 200}.${Math.floor(rand() * 200) + 20}`,
  })
}

teamUsers.forEach((team, teamIndex) => {
  const rankSkill = 1 - teamIndex / teamUsers.length
  const teamSkill = clamp(rankSkill * 0.82 + rand() * 0.24, 0.05, 0.98)

  publicChallengeSeeds.forEach((challenge, challengeIndex) => {
    const releaseTime =
      config.startTime + (challenge.releaseOffsetHours ?? 0) * HOUR
    const probability = clamp(
      0.08 + teamSkill * 0.9 - challenge.difficulty * 0.58 + rand() * 0.16,
      0.02,
      0.96
    )

    if (rand() > probability) return

    const solveWindow = Math.max(1, latestSolveTime - releaseTime)
    const earlyBias = clamp(0.55 + teamSkill * 0.9, 0.6, 1.35)
    const progress = Math.pow(rand(), earlyBias)
    const jitter = rand() * 20 * 60_000
    addSolve(
      team,
      challenge,
      Math.floor(releaseTime + solveWindow * progress + jitter),
      challengeIndex
    )
  })
})

publicChallengeSeeds.forEach((challenge, challengeIndex) => {
  const releaseTime =
    config.startTime + (challenge.releaseOffsetHours ?? 0) * HOUR
  for (const team of teamUsers.slice(0, 5)) {
    addSolve(
      team,
      challenge,
      releaseTime + (challengeIndex + 1) * 13 * 60_000 + rand() * HOUR,
      challengeIndex
    )
  }
})

solveRows.sort((a, b) => a.createdat.localeCompare(b.createdat))

const submissionLogRows: SubmissionLogSeed[] = []

const attemptIp = (userId: string, index: number) => {
  const userPart = Number(userId.slice(-3)) || index % 200
  return `10.${(index % 160) + 40}.${userPart % 200}.${((index * 37) % 200) + 20}`
}

solveRows.forEach((solve, index) => {
  submissionLogRows.push({
    id: `submission-log-${solve.id}-correct`,
    kind: 'flag',
    challenge_id: solve.challengeid,
    user_id: solve.userid,
    ip: solve.submissionip,
    result: 'correct',
    details: {
      submittedFlag: challengeFlagById.get(solve.challengeid) ?? 'unknown',
    },
    related_id: solve.id,
    created_at: solve.createdat,
  })

  if (index % 3 === 0) {
    submissionLogRows.push({
      id: `submission-log-${solve.id}-incorrect`,
      kind: 'flag',
      challenge_id: solve.challengeid,
      user_id: solve.userid,
      ip: attemptIp(solve.userid, index),
      result: 'incorrect',
      details: {
        submittedFlag: `rctf{wrong_${String(index).padStart(3, '0')}}`,
      },
      related_id: null,
      created_at: shiftIso(solve.createdat, -8 * 60_000),
    })
  }

  if (index % 7 === 0) {
    submissionLogRows.push({
      id: `submission-log-${solve.id}-rate-limited`,
      kind: 'flag',
      challenge_id: solve.challengeid,
      user_id: solve.userid,
      ip: attemptIp(solve.userid, index + 17),
      result: 'rate_limited',
      details: {
        submittedFlag: `rctf{rate_limited_${String(index).padStart(3, '0')}}`,
      },
      related_id: null,
      created_at: shiftIso(solve.createdat, -4 * 60_000),
    })
  }

  if (index % 11 === 0) {
    submissionLogRows.push({
      id: `submission-log-${solve.id}-already-solved`,
      kind: 'flag',
      challenge_id: solve.challengeid,
      user_id: solve.userid,
      ip: solve.submissionip,
      result: 'already_solved',
      details: {
        submittedFlag: challengeFlagById.get(solve.challengeid) ?? 'unknown',
      },
      related_id: solve.id,
      created_at: shiftIso(solve.createdat, 12 * 60_000),
    })
  }
})

const adminBotResults: SubmissionLogSeed['result'][] = [
  'queued',
  'active_job',
  'rate_limited',
  'invalid_input',
  'bad_instancer_state',
]

teamUsers.slice(0, 24).forEach((team, index) => {
  const challenge = publicChallengeSeeds[index % publicChallengeSeeds.length]!
  const result = adminBotResults[index % adminBotResults.length]!
  const createdAt = Math.min(
    latestSolveTime,
    config.startTime + HOUR + index * 17 * 60_000
  )

  submissionLogRows.push({
    id: `submission-log-admin-bot-${index + 1}`,
    kind: 'admin_bot',
    challenge_id: challenge.id,
    user_id: team.id,
    ip: `172.20.${(index % 80) + 10}.${((index * 29) % 200) + 20}`,
    result,
    details: {
      inputs: {
        url: `https://${slug(team.name)}.dev.rctf.local/adminbot/${slug(challenge.name)}`,
      },
      configRevision: `dev-seed-${(index % 3) + 1}`,
      ...(result === 'invalid_input'
        ? {
            field: 'url',
            error: 'Input "url" does not match the required format',
          }
        : {}),
      ...(result === 'bad_instancer_state'
        ? { error: 'Admin bot requires a running challenge instance' }
        : {}),
    },
    related_id: null,
    created_at: toIso(createdAt),
  })
})

submissionLogRows.sort((a, b) => a.created_at.localeCompare(b.created_at))

const memberRows = teamUsers.flatMap((team, teamIndex) => {
  const memberCount = teamIndex % 4
  return Array.from({ length: memberCount }, (_, memberIndex) => ({
    id: `${team.id}-member-${memberIndex + 1}`,
    userid: team.id,
    email: `${slug(team.name)}-${memberIndex + 1}@members.dev.rctf.local`,
  }))
})

assertDevStorageTarget(config.database)

const { client, db } = createDatabase(config.database.sql)
const redis = await createRedis()

try {
  const relationExists = async (relationName: string) =>
    await client<
      {
        exists: boolean
      }[]
    >`SELECT to_regclass(${`public.${relationName}`}) IS NOT NULL AS "exists"`.then(
      rows => rows[0]?.exists ?? false
    )

  const columnExists = async (tableName: string, columnName: string) =>
    await client<
      {
        exists: boolean
      }[]
    >`
        SELECT EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = ${tableName}
            AND column_name = ${columnName}
        ) AS "exists"
      `.then(rows => rows[0]?.exists ?? false)

  const insertSubmissionLogs = async (includeDetails: boolean) => {
    const payload = JSON.stringify(submissionLogRows)

    if (includeDetails) {
      await client`
        INSERT INTO submission_logs (
          id,
          kind,
          challenge_id,
          user_id,
          ip,
          result,
          details,
          related_id,
          created_at
        )
        SELECT
          id,
          kind,
          challenge_id,
          user_id,
          ip,
          result,
          details,
          related_id,
          created_at
        FROM jsonb_to_recordset(${payload}::jsonb)
          AS seeded_log(
            id text,
            kind text,
            challenge_id text,
            user_id text,
            ip text,
            result text,
            details jsonb,
            related_id text,
            created_at timestamptz
          )
      `
      return
    }

    await client`
      INSERT INTO submission_logs (
        id,
        kind,
        challenge_id,
        user_id,
        ip,
        result,
        related_id,
        created_at
      )
      SELECT
        id,
        kind,
        challenge_id,
        user_id,
        ip,
        result,
        related_id,
        created_at
      FROM jsonb_to_recordset(${payload}::jsonb)
        AS seeded_log(
          id text,
          kind text,
          challenge_id text,
          user_id text,
          ip text,
          result text,
          related_id text,
          created_at timestamptz
        )
    `
  }

  const submissionLogsTableExists = await relationExists('submission_logs')
  const submissionLogsDetailsColumnExists =
    submissionLogsTableExists &&
    (await columnExists('submission_logs', 'details'))

  await redis.flushdb()
  if (submissionLogsTableExists) {
    await client`DELETE FROM submission_logs`
  }

  await db.delete(adminBotJobs)
  await db.delete(solves)
  await db.delete(userMembers)
  await db.delete(challenges)
  await db.delete(users)
  await db.delete(settings)

  await db.insert(users).values(seedUsers)
  await db.insert(userMembers).values(memberRows)
  await db.insert(challenges).values(challengeRows)
  await db.insert(solves).values(solveRows)
  if (submissionLogsTableExists && submissionLogRows.length > 0) {
    await insertSubmissionLogs(submissionLogsDetailsColumnExists)
  }

  await db.insert(settings).values({
    id: 'value-0',
    data: {
      ctfName: 'rCTF Dev Arena',
      homeContent:
        'Welcome to the seeded rCTF development arena.\n\n<timer></timer>',
      meta: {
        description: 'Seeded local rCTF development instance',
        imageUrl: 'https://example.com/dev.png',
      },
      sponsors: [
        {
          name: 'OtterSec',
          icon: 'https://osec.io/favicon.ico',
          description: 'Seed sponsor entry for local UI testing.',
          url: 'https://osec.io',
        },
      ],
    },
  })

  const calculated = await calculateLeaderboard(db)
  await cacheLeaderboardAndGraph(db, redis, calculated)

  const adminTeamToken = await createToken(TokenKind.Team, 'dev-admin')
  const adminAuthToken = await createToken(TokenKind.Auth, 'dev-admin')
  const firstTeamToken = await createToken(TokenKind.Team, teamUsers[0]!.id)
  const pendingTeams = await Promise.all(
    pendingTeamRegistrations.map(async team => {
      const verificationToken = await createLoginVerification(redis, {
        kind: 'register',
        name: team.name,
        email: team.email,
        division: team.division,
      })

      return {
        ...team,
        verificationToken,
        verifyUrl: `http://127.0.0.1:5173/verify?token=${encodeURIComponent(
          verificationToken
        )}`,
      }
    })
  )

  const output = {
    generatedAt: new Date().toISOString(),
    webUrl: 'http://127.0.0.1:5173',
    apiUrl: 'http://127.0.0.1:3000',
    admin: {
      email: 'admin@dev.rctf.local',
      teamToken: adminTeamToken,
      authToken: adminAuthToken,
      loginUrl: `http://127.0.0.1:5173/login?token=${encodeURIComponent(
        adminTeamToken
      )}`,
    },
    sampleTeam: {
      name: teamUsers[0]!.name,
      email: teamUsers[0]!.email,
      teamToken: firstTeamToken,
      loginUrl: `http://127.0.0.1:5173/login?token=${encodeURIComponent(
        firstTeamToken
      )}`,
    },
    pendingTeams,
    counts: {
      users: seedUsers.length,
      teams: teamUsers.length,
      pendingTeams: pendingTeams.length,
      bannedTeams: teamUsers.filter(user => user.banned).length,
      members: memberRows.length,
      challenges: challengeRows.length,
      publicChallenges: publicChallengeSeeds.length,
      solves: solveRows.length,
      submissionLogs: submissionLogsTableExists ? submissionLogRows.length : 0,
      leaderboardRows: calculated.users.length,
    },
  }

  await writeFile(seedOutputPath, `${JSON.stringify(output, null, 2)}\n`)

  console.log(`Seeded ${output.counts.teams} teams.`)
  console.log(`Seeded ${output.counts.pendingTeams} pending teams.`)
  console.log(`Seeded ${output.counts.challenges} challenges.`)
  console.log(`Seeded ${output.counts.solves} solves.`)
  if (submissionLogsTableExists) {
    console.log(`Seeded ${output.counts.submissionLogs} submission logs.`)
  }
  console.log(`Admin login: ${output.admin.loginUrl}`)
  console.log(`Seed details written to ${seedOutputPath}`)
} finally {
  await redis.quit().catch(() => {})
  await client.end({ timeout: 1 }).catch(() => {})
}
