site_name: rCTF Documentation
site_description: rCTF Documentation
site_author: redpwn
site_url: https://rctf.osec.io

repo_name: GitHub
repo_url: https://github.com/otter-sec/rctf
edit_uri: blob/master/docs/content/

docs_dir: content

theme:
  name: material
  language: en
  features:
    - instant
    - navigation.sections
  palette:
    scheme: slate
    primary: blue
    accent: blue

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - def_list
  - toc:
      permalink: '#'
