name: Build admin-bot

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/docker-build.yaml"
      - ".github/workflows/admin-bot.yaml"
      - "apps/admin-bot/**"
      - "packages/**"
      - "deploy/admin-bot/**"

concurrency:
  group: admin-bot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: ${{ github.repository }}/admin-bot
      dockerfile: deploy/admin-bot/Dockerfile
      # bun supports only amd64 and arm64
      platforms: linux/amd64,linux/arm64
    permissions:
      contents: read
      packages: write
    secrets: inherit
