name: Build admin-bot

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/_docker-build.yml"
      - ".github/workflows/build-admin-bot.yml"
      - ".github/workflows/test.yml"
      - ".github/actions/setup-bun-deps/action.yml"
      - "apps/admin-bot/**"
      - "packages/**"
      - "deploy/admin-bot/**"

permissions:
  contents: read

concurrency:
  group: admin-bot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-and-push:
    needs: tests
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: ${{ github.repository }}/admin-bot
      dockerfile: deploy/admin-bot/Dockerfile
      # bun supports only amd64 and arm64
      platforms-matrix: |
        [
          {"platform": "linux/amd64", "runner": "ubuntu-24.04"},
          {"platform": "linux/arm64", "runner": "ubuntu-24.04-arm"}
        ]
    permissions:
      contents: read
      packages: write
    secrets: inherit
