name: Build docs

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/_docker-build.yml"
      - ".github/workflows/build-docs.yml"
      - ".github/workflows/test.yml"
      - ".github/actions/setup-bun-deps/action.yml"
      - "apps/docs/**"
      - "packages/**"
      - "deploy/docs/**"

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-and-push:
    needs: tests
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: ${{ github.repository }}/docs
      dockerfile: deploy/docs/Dockerfile
      # runtime image is alpine so all platforms can be used
      platforms-matrix: |
        [
          {"platform": "linux/amd64", "runner": "ubuntu-24.04"},
          {"platform": "linux/arm64", "runner": "ubuntu-24.04-arm"},
          {"platform": "linux/386", "runner": "ubuntu-24.04"},
          {"platform": "linux/arm/v6", "runner": "ubuntu-24.04"},
          {"platform": "linux/arm/v7", "runner": "ubuntu-24.04"},
          {"platform": "linux/ppc64le", "runner": "ubuntu-24.04"}
        ]
    permissions:
      contents: read
      packages: write
    secrets: inherit
