name: Build rctf

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/_docker-build.yml"
      - ".github/workflows/build-rctf.yml"
      - ".github/workflows/test.yml"
      - ".github/actions/setup-bun-deps/action.yml"
      - "package.json"
      - "apps/api/**"
      - "apps/web/**"
      - "packages/**"
      - "deploy/rctf/**"

permissions:
  contents: read

concurrency:
  group: rctf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-and-push:
    needs: tests
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: ${{ github.repository }}
      dockerfile: deploy/rctf/Dockerfile
      # bun supports only amd64 and arm64
      platforms-matrix: |
        [
          {"platform": "linux/amd64", "runner": "ubuntu-24.04"},
          {"platform": "linux/arm64", "runner": "ubuntu-24.04-arm"}
        ]
    permissions:
      contents: read
      packages: write
    secrets: inherit
