name: Build docker-instancer

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/docker-build.yaml"
      - ".github/workflows/docker-instancer.yaml"
      - "apps/docker-instancer/**"
      - "deploy/docker-instancer/Dockerfile"

concurrency:
  group: docker-instancer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: ${{ github.repository }}/docker-instancer
      dockerfile: deploy/docker-instancer/Dockerfile
      # uv supports only amd64 and arm64
      platforms: linux/amd64,linux/arm64
    permissions:
      contents: read
      packages: write
    secrets: inherit
