name: Build docs

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/docker-build.yaml"
      - ".github/workflows/docs.yaml"
      - "apps/docs/**"
      - "packages/**"
      - "deploy/docs/Dockerfile"
      - "deploy/docs/nginx-static.conf"

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: ${{ github.repository }}/docs
      dockerfile: deploy/docs/Dockerfile
      # runtime image is alpine so all platforms can be used
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
    permissions:
      contents: read
      packages: write
    secrets: inherit
