name: Build rctf

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/docker-build.yaml"
      - ".github/workflows/rctf.yaml"
      - "package.json"
      - "apps/api/**"
      - "apps/web/**"
      - "packages/**"
      - "deploy/rctf/**"

concurrency:
  group: rctf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: ${{ github.repository }}
      dockerfile: deploy/rctf/Dockerfile
      # bun supports only amd64 and arm64
      platforms: linux/amd64,linux/arm64
    permissions:
      contents: read
      packages: write
    secrets: inherit
